### ISSUE TITLE
Create a pressbooks tests github action

### ISSUE THREAD

**Issue by arzola** [pressbooks/pressbooks#2518]
I was thinking that probably it could be a good idea to avoid duplication to have a centralized GitHub action that handle the PHP experimental paths and also reduce duplication amongs Pressbooks repos

### Current setup in each pressbooks repo
```
- name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php }}
        tools: composer:v1
        coverage: pcov
        extensions: imagick
      if: matrix.experimental == false

    - name: Setup PHP with Composer 2
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php }}
        tools: composer
        coverage: pcov
        extensions: imagick
      if: matrix.experimental == true

- name: Install PHP dependencies
      run: |
        export PATH="$HOME/.composer/vendor/bin:$PATH"
        composer install --no-interaction
        ulimit -n 4096

- name: Run PHP CodeSniffer
      run: composer standards
      if: matrix.experimental == false

    - name: Install WP tests
      run: bash bin/install-wp-tests.sh wordpress_test root root localhost ${{ matrix.wordpress }}

    - name: Run PHP Tests
      run: composer test
      if: matrix.experimental == true && matrix.wordpress != 'trunk'

    - name: Run PHP Tests with PHPUnit 9
      run: |
        composer remove --dev codeception/*
        composer remove --dev lucatume/wp-browser
        composer remove --dev phpunit/phpunit
        composer update --dev yoast/phpunit-polyfills --with-dependencies --ignore-platform-reqs
        vendor/bin/phpunit --configuration phpunit9.xml
      if: matrix.wordpress == 'trunk'

    - name: Run PHP Tests and PCOV
      run: |
        composer require pcov/clobber
        vendor/bin/pcov clobber
        vendor/bin/phpunit --configuration phpunit.xml --coverage-clover coverage.xml
      if: matrix.experimental == false
```

The code above is almost identical in all our repos I think it could be centralized in a pressbooks-test-setup GitHub actions

### Proof of concept
```
- name: Pressbooks Tests Setup
      uses: pressbooks/setup-pressbooks-tests@v1
```

Idea 
https://docs.github.com/en/actions/creating-actions/creating-a-composite-action

**Comment by SteelWagstaff** [comment]
@arzola is this still relevant or can it be closed?

**Comment by arzola** [comment]
I think we can close this we centralized this operation in https://github.com/pressbooks/reusable-workflows/blob/main/.github/workflows/pb-plugin-tests.yml

**Comment by arzola** [comment]
It was implemented in a different way though

```
plugin-tests:
    uses: pressbooks/reusable-workflows/.github/workflows/pb-plugin-tests.yml@main
    secrets: inherit
    with:
      requires_pressbooks: true
      use_mariadb: true
```
